Specify "refs/heads/__virtme__" in git push
When using "vng --build --build-host user@host", I get:

    error: The destination you provided is not a full refname (i.e.,
    starting with "refs/"). We tried to guess what you meant by:

    - Looking for a ref that matches '__virtme__' on the remote side.
    - Checking if the <src> being pushed ('HEAD')
      is a ref in "refs/{heads,tags}/". If so we add a corresponding
      refs/{heads,tags}/ prefix on the remote side.

    Neither worked, so we gave up. You must fully qualify the ref.
    hint: The <src> part of the refspec is a commit object.
    hint: Did you mean to create a new branch by pushing to
    hint: 'HEAD:refs/heads/__virtme__'?
    error: failed to push some refs to 'host:~/.virtme'

The build host is running git 2.46.0, and the git checkout on the host
was newly created, thus the source of this error (no __virtme__ branch).
Explicitly push it as a branch, following the hint in the error message.

Signed-off-by: Stephen Brennan <stephen@brennan.io>