virtme/commands/run: Fix TypeError
`re.search(...)` expects a string as the second argument, therefore
let's convert the Path into a string.

  $ ./vng -r
  Traceback (most recent call last):
    File "/home/mhartmay/storage/git/virtme-ng/virtme-run", line 18, in <module>
      sys.exit(run.main())
               ^^^^^^^^^^
    File "/home/mhartmay/storage/git/virtme-ng/virtme/commands/run.py", line 2028, in main
      return do_it()
             ^^^^^^^
    File "/home/mhartmay/storage/git/virtme-ng/virtme/commands/run.py", line 1198, in do_it
      kernel = find_kernel_and_mods(arch, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/mhartmay/storage/git/virtme-ng/virtme/commands/run.py", line 575, in find_kernel_and_mods
      kver = get_kernel_version(kimg, img_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/mhartmay/storage/git/virtme-ng/virtme/commands/run.py", line 520, in get_kernel_version
      match = re.search(rf"{img_name}-({version_pattern})", path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/re/__init__.py", line 177, in search
      return _compile(pattern, flags).search(string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: expected string or bytes-like object, got 'PosixPath'

Fixes: 2290a6a7e3c4 ("commands: run.py: Resolve symlinks on get_kernel_version")
Signed-off-by: Marc Hartmayer <mhartmay@linux.ibm.com>