resources: Support importlib_resources with python 3.10
importlib.resources.files() expects a package, not a module. In python
3.10, __name__ resolves to 'virtme.resources', which is a module, not a
package, which triggers this error:

  TypeError: 'virtme.resources' is not a package

Fix by passing the package to importlib_resources.files().

Signed-off-by: Andrea Righi <arighi@nvidia.com>