virtme: fix traceback with --kdir when .config doesn't exist
Reproducer:
```
$ mkdir -p testdir/arch/x86/boot
$ touch testdir/arch/x86/boot/bzImage
$ virtme-run --kdir testdir
Traceback (most recent call last):
  File "/usr/bin/virtme-run", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/virtme/commands/run.py", line 1388, in main
    return do_it()
           ^^^^^^^
  File "/usr/lib/python3.12/site-packages/virtme/commands/run.py", line 803, in do_it
    kernel = find_kernel_and_mods(arch, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/virtme/commands/run.py", line 486, in find_kernel_and_mods
    kernel.config is not None
    ^^^^^^^^^^^^^
AttributeError: 'Kernel' object has no attribute 'config'
```

Fix the above by initializing kernel.config right away.

Signed-off-by: Ondrej Mosnáček <omosnacek@gmail.com>